version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orchid
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  irrigation:
    build: 
      context: ./irigation_b
    ports:
      - "5006:5006"
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:root@mysql-db/orchid
    depends_on:
      - mysql-db
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
